export const FORM_TEMPLATES_DATA = {
  briefing: {
    name: 'Briefing para Agência',
    description: 'Formulário de briefing detalhado para captar requisitos',
    icon: '📋',
    category: 'briefing',
    fields: [
      { label: 'Qual é o nome do seu projeto?', type: 'short_text', required: true, order: 0 },
      { label: 'Descreva os objetivos do projeto', type: 'long_text', required: true, order: 1 },
      { label: 'Qual é o público-alvo?', type: 'long_text', required: true, order: 2 },
      { label: 'Qual é o orçamento estimado?', type: 'currency', required: false, order: 3 },
      {
        label: 'Qual é a timeline esperada?',
        type: 'single_choice',
        required: true,
        options: [
          { label: 'Até 1 mês', value: '1m' },
          { label: '1-3 meses', value: '3m' },
          { label: '3-6 meses', value: '6m' },
          { label: '+6 meses', value: '+6m' },
        ],
        order: 4,
      },
      { label: 'Link de referências (opcional)', type: 'url', required: false, order: 5 },
      {
        label: 'Entregáveis esperados',
        type: 'multiple_choice',
        required: true,
        options: [
          { label: 'Design', value: 'design' },
          { label: 'Desenvolvimento', value: 'dev' },
          { label: 'Copywriting', value: 'copy' },
          { label: 'Marketing', value: 'marketing' },
        ],
        order: 6,
      },
    ],
    results: [
      { title: 'Briefing Recebido', description: 'Obrigado! Entraremos em contato em breve.' },
    ],
  },
  nps: {
    name: 'Pesquisa NPS',
    description: 'Meça a satisfação e lealdade de clientes',
    icon: '📊',
    category: 'nps',
    fields: [
      {
        label: 'Em uma escala de 0 a 10, qual a probabilidade de recomendar nosso serviço?',
        type: 'nps',
        required: true,
        order: 0,
      },
      {
        label: 'Por que deu essa nota?',
        type: 'long_text',
        required: false,
        order: 1,
      },
      {
        label: 'O que podemos melhorar?',
        type: 'long_text',
        required: false,
        order: 2,
      },
      {
        label: 'Qual é o seu email?',
        type: 'email',
        required: false,
        order: 3,
      },
    ],
    results: [
      { title: 'Obrigado!', description: 'Sua resposta foi muito importante para nós.' },
    ],
  },
  diagnostic: {
    name: 'Diagnóstico',
    description: 'Diagnóstico com lógica e resultados personalizados',
    icon: '🔍',
    category: 'diagnostic',
    fields: [
      {
        label: 'Como você se sente hoje?',
        type: 'rating',
        required: true,
        order: 0,
      },
      {
        label: 'Selecione os sintomas que você apresenta',
        type: 'multiple_choice',
        required: true,
        options: [
          { label: 'Cansaço', value: 'tired' },
          { label: 'Ansiedade', value: 'anxiety' },
          { label: 'Dificuldade de concentração', value: 'focus' },
          { label: 'Insônia', value: 'sleep' },
        ],
        order: 1,
      },
      {
        label: 'Há quanto tempo sente esses sintomas?',
        type: 'single_choice',
        required: true,
        options: [
          { label: '1-2 semanas', value: 'weeks' },
          { label: '1 mês', value: 'month' },
          { label: '3 meses', value: '3months' },
          { label: 'Mais de 3 meses', value: 'longer' },
        ],
        order: 2,
      },
    ],
    results: [
      { title: 'Diagnóstico Leve', description: 'Recomendamos repouso e atenção à saúde mental.' },
      { title: 'Diagnóstico Moderado', description: 'Procure um profissional de saúde.' },
    ],
  },
  onboarding: {
    name: 'Onboarding',
    description: 'Formulário de integração para novos usuários',
    icon: '👋',
    category: 'onboarding',
    fields: [
      { label: 'Qual é o seu nome?', type: 'short_text', required: true, order: 0 },
      { label: 'Qual é o seu email?', type: 'email', required: true, order: 1 },
      { label: 'Qual é a sua empresa?', type: 'short_text', required: true, order: 2 },
      {
        label: 'Qual é o seu papel?',
        type: 'dropdown',
        required: true,
        options: [
          { label: 'Executivo', value: 'exec' },
          { label: 'Gerente', value: 'manager' },
          { label: 'Colaborador', value: 'employee' },
          { label: 'Outro', value: 'other' },
        ],
        order: 3,
      },
      {
        label: 'O que mais lhe interessa?',
        type: 'multiple_choice',
        required: true,
        options: [
          { label: 'Automação', value: 'automation' },
          { label: 'Analytics', value: 'analytics' },
          { label: 'Integração', value: 'integration' },
          { label: 'Relatórios', value: 'reports' },
        ],
        order: 4,
      },
    ],
    results: [
      { title: 'Bem-vindo!', description: 'Sua conta foi criada com sucesso. Vamos começar!' },
    ],
  },
  evaluation: {
    name: 'Avaliação de Performance',
    description: 'Avalie colaboradores com escala e pontuação',
    icon: '⭐',
    category: 'assessment',
    fields: [
      { label: 'Nome do avaliado', type: 'short_text', required: true, order: 0 },
      {
        label: 'Assiduidade e pontualidade',
        type: 'rating',
        required: true,
        order: 1,
      },
      {
        label: 'Qualidade do trabalho',
        type: 'rating',
        required: true,
        order: 2,
      },
      {
        label: 'Colaboração em equipe',
        type: 'rating',
        required: true,
        order: 3,
      },
      {
        label: 'Principais pontos fortes',
        type: 'long_text',
        required: false,
        order: 4,
      },
      {
        label: 'Pontos de melhoria',
        type: 'long_text',
        required: false,
        order: 5,
      },
    ],
    results: [
      { title: 'Avaliação Registrada', description: 'Obrigado por completar a avaliação.' },
    ],
  },
  survey: {
    name: 'Pesquisa Interna',
    description: 'Pesquisa de clima e cultura organizacional',
    icon: '📝',
    category: 'internal_research',
    fields: [
      {
        label: 'Como você se sente no seu ambiente de trabalho?',
        type: 'single_choice',
        required: true,
        options: [
          { label: 'Muito satisfeito', value: '5' },
          { label: 'Satisfeito', value: '4' },
          { label: 'Neutro', value: '3' },
          { label: 'Insatisfeito', value: '2' },
          { label: 'Muito insatisfeito', value: '1' },
        ],
        order: 0,
      },
      {
        label: 'Os valores da empresa são claros?',
        type: 'single_choice',
        required: true,
        options: [
          { label: 'Muito claro', value: '5' },
          { label: 'Claro', value: '4' },
          { label: 'Mais ou menos', value: '3' },
          { label: 'Pouco claro', value: '2' },
          { label: 'Não é claro', value: '1' },
        ],
        order: 1,
      },
      {
        label: 'Você se sente reconhecido pelo seu trabalho?',
        type: 'single_choice',
        required: true,
        options: [
          { label: 'Sempre', value: '5' },
          { label: 'Frequentemente', value: '4' },
          { label: 'Às vezes', value: '3' },
          { label: 'Raramente', value: '2' },
          { label: 'Nunca', value: '1' },
        ],
        order: 2,
      },
      {
        label: 'Sugestões de melhorias',
        type: 'long_text',
        required: false,
        order: 3,
      },
    ],
    results: [
      { title: 'Pesquisa Enviada', description: 'Obrigado por participar da pesquisa de clima.' },
    ],
  },
  'lead-capture': {
    name: 'Captação de Leads',
    description: 'Formulário para captura de contatos qualificados',
    icon: '📧',
    category: 'lead_capture',
    fields: [
      { label: 'Nome', type: 'short_text', required: true, order: 0 },
      { label: 'Email', type: 'email', required: true, order: 1 },
      { label: 'Telefone', type: 'phone', required: false, order: 2 },
      { label: 'Empresa', type: 'short_text', required: true, order: 3 },
      {
        label: 'Cargo',
        type: 'dropdown',
        required: true,
        options: [
          { label: 'CEO/Diretor', value: 'ceo' },
          { label: 'Gerente', value: 'manager' },
          { label: 'Especialista', value: 'specialist' },
          { label: 'Outro', value: 'other' },
        ],
        order: 4,
      },
      {
        label: 'Como você nos conheceu?',
        type: 'single_choice',
        required: true,
        options: [
          { label: 'Google', value: 'google' },
          { label: 'LinkedIn', value: 'linkedin' },
          { label: 'Indicação', value: 'referral' },
          { label: 'Redes Sociais', value: 'social' },
          { label: 'Outro', value: 'other' },
        ],
        order: 5,
      },
    ],
    results: [
      { title: 'Lead Capturado!', description: 'Obrigado! Entraremos em contato em breve.' },
    ],
  },
  intake: {
    name: 'Anamnese',
    description: 'Formulário de intake para serviços profissionais',
    icon: '📌',
    category: 'intake',
    fields: [
      { label: 'Nome completo', type: 'short_text', required: true, order: 0 },
      { label: 'Data de nascimento', type: 'date', required: true, order: 1 },
      { label: 'Email', type: 'email', required: true, order: 2 },
      { label: 'Telefone', type: 'phone', required: true, order: 3 },
      { label: 'Motivo da consulta', type: 'long_text', required: true, order: 4 },
      {
        label: 'Já passou por tratamento?',
        type: 'single_choice',
        required: true,
        options: [
          { label: 'Sim', value: 'yes' },
          { label: 'Não', value: 'no' },
        ],
        order: 5,
      },
      { label: 'Histórico de saúde', type: 'long_text', required: false, order: 6 },
      {
        label: 'Autoriza coleta de dados?',
        type: 'checkbox',
        required: true,
        helpText: 'Sim, autorizo a coleta de dados pessoais',
        order: 7,
      },
    ],
    results: [
      { title: 'Intake Registrado', description: 'Sua avaliação foi salva. Em breve entraremos em contato.' },
    ],
  },
};